DROP TABLE IF EXISTS PostLikes;
DROP TABLE IF EXISTS TopicLikes;
DROP TABLE IF EXISTS Post;
DROP TABLE IF EXISTS Topic;
DROP TABLE IF EXISTS Forum;
DROP TABLE IF EXISTS Person;

CREATE TABLE Person (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	username VARCHAR(10) NOT NULL UNIQUE,
	stuId VARCHAR(10) NULL
);

CREATE TABLE Forum (
	forum_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Topic (
	topic_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	forum_id INTEGER NOT NULL,
	person_id INTEGER NOT NULL,
	title VARCHAR(255) NOT NULL,
	text VARCHAR(2048) NOT NULL,
	last_post_time TIMESTAMP NULL,
	total_posts INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (forum_id) REFERENCES Forum(forum_id)
);

CREATE TABLE Post (
	post_id INTEGER PRIMARY KEY AUTO_INCREMENT,
	topic_id INTEGER NOT NULL,
	person_id INTEGER NOT NULL,
	post_number INTEGER NOT NULL,
	posted_at TIMESTAMP NOT NULL,
	text VARCHAR(2048) NOT NULL,
	FOREIGN KEY (topic_id) REFERENCES Topic(topic_id),
	FOREIGN KEY (person_id) REFERENCES Person(id)
);

CREATE TABLE TopicLikes (
	topic_id INTEGER NOT NULL,
	person_id INTEGER NOT NULL,
	PRIMARY KEY (topic_id, person_id),
	FOREIGN KEY (topic_id) REFERENCES Topic(topic_id),
	FOREIGN KEY (person_id) REFERENCES Person(id)
);

CREATE TABLE PostLikes (
	post_id INTEGER NOT NULL,
	person_id INTEGER NOT NULL,
	PRIMARY KEY (post_id, person_id),
	FOREIGN KEY (person_id) REFERENCES Person (id)
);
